pub const OpcodeDesc = struct {
    name: [:0]const u8,
    match: u32,
    mask: u32,
    operands: []const Operand,
    variable_fields: []const Field,
    extensions: []const Extension,
};

pub const opcodes: []const OpcodeDesc = &.{
    .{
        .name = "mul",
        .match = 0x2000033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_m},
    },
    .{
        .name = "mulh",
        .match = 0x2001033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_m},
    },
    .{
        .name = "mulhsu",
        .match = 0x2002033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_m},
    },
    .{
        .name = "mulhu",
        .match = 0x2003033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_m},
    },
    .{
        .name = "div",
        .match = 0x2004033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_m},
    },
    .{
        .name = "divu",
        .match = 0x2005033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_m},
    },
    .{
        .name = "rem",
        .match = 0x2006033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_m},
    },
    .{
        .name = "remu",
        .match = 0x2007033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_m},
    },
    .{
        .name = "lui",
        .match = 0x37,
        .mask = 0x7f,
        .operands = &.{ .rd, .imm32 },
        .variable_fields = &.{ .rd, .imm20 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "auipc",
        .match = 0x17,
        .mask = 0x7f,
        .operands = &.{ .rd, .imm32 },
        .variable_fields = &.{ .rd, .imm20 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "jal",
        .match = 0x6f,
        .mask = 0x7f,
        .operands = &.{ .rd, .imm21 },
        .variable_fields = &.{ .rd, .jimm20 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "jalr",
        .match = 0x67,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "beq",
        .match = 0x63,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm13 },
        .variable_fields = &.{ .bimm12hi, .rs1, .rs2, .bimm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "bne",
        .match = 0x1063,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm13 },
        .variable_fields = &.{ .bimm12hi, .rs1, .rs2, .bimm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "blt",
        .match = 0x4063,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm13 },
        .variable_fields = &.{ .bimm12hi, .rs1, .rs2, .bimm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "bge",
        .match = 0x5063,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm13 },
        .variable_fields = &.{ .bimm12hi, .rs1, .rs2, .bimm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "bltu",
        .match = 0x6063,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm13 },
        .variable_fields = &.{ .bimm12hi, .rs1, .rs2, .bimm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "bgeu",
        .match = 0x7063,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm13 },
        .variable_fields = &.{ .bimm12hi, .rs1, .rs2, .bimm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "lb",
        .match = 0x3,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "lh",
        .match = 0x1003,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "lw",
        .match = 0x2003,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "lbu",
        .match = 0x4003,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "lhu",
        .match = 0x5003,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sb",
        .match = 0x23,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm12 },
        .variable_fields = &.{ .imm12hi, .rs1, .rs2, .imm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sh",
        .match = 0x1023,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm12 },
        .variable_fields = &.{ .imm12hi, .rs1, .rs2, .imm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sw",
        .match = 0x2023,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm12 },
        .variable_fields = &.{ .imm12hi, .rs1, .rs2, .imm12lo },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "addi",
        .match = 0x13,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "slti",
        .match = 0x2013,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sltiu",
        .match = 0x3013,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "xori",
        .match = 0x4013,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "ori",
        .match = 0x6013,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "andi",
        .match = 0x7013,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "add",
        .match = 0x33,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sub",
        .match = 0x40000033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sll",
        .match = 0x1033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "slt",
        .match = 0x2033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sltu",
        .match = 0x3033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "xor",
        .match = 0x4033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "srl",
        .match = 0x5033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sra",
        .match = 0x40005033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "or",
        .match = 0x6033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "and",
        .match = 0x7033,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "fence",
        .match = 0xf,
        .mask = 0x707f,
        .operands = &.{ .fm, .pred, .succ, .rs1, .rd },
        .variable_fields = &.{ .fm, .pred, .succ, .rs1, .rd },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "ecall",
        .match = 0x73,
        .mask = 0xffffffff,
        .operands = &.{},
        .variable_fields = &.{},
        .extensions = &.{.rv_i},
    },
    .{
        .name = "ebreak",
        .match = 0x100073,
        .mask = 0xffffffff,
        .operands = &.{},
        .variable_fields = &.{},
        .extensions = &.{.rv_i},
    },
    .{
        .name = "flw",
        .match = 0x2007,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fsw",
        .match = 0x2027,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm12 },
        .variable_fields = &.{ .imm12hi, .rs1, .rs2, .imm12lo },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fmadd_s",
        .match = 0x43,
        .mask = 0x600007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fmsub_s",
        .match = 0x47,
        .mask = 0x600007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fnmsub_s",
        .match = 0x4b,
        .mask = 0x600007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fnmadd_s",
        .match = 0x4f,
        .mask = 0x600007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fadd_s",
        .match = 0x53,
        .mask = 0xfe00007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fsub_s",
        .match = 0x8000053,
        .mask = 0xfe00007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fmul_s",
        .match = 0x10000053,
        .mask = 0xfe00007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fdiv_s",
        .match = 0x18000053,
        .mask = 0xfe00007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fsqrt_s",
        .match = 0x58000053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fsgnj_s",
        .match = 0x20000053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fsgnjn_s",
        .match = 0x20001053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fsgnjx_s",
        .match = 0x20002053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fmin_s",
        .match = 0x28000053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fmax_s",
        .match = 0x28001053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fcvt_w_s",
        .match = 0xc0000053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fcvt_wu_s",
        .match = 0xc0100053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fmv_x_w",
        .match = 0xe0000053,
        .mask = 0xfff0707f,
        .operands = &.{ .rd, .rs1 },
        .variable_fields = &.{ .rd, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "feq_s",
        .match = 0xa0002053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "flt_s",
        .match = 0xa0001053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fle_s",
        .match = 0xa0000053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fclass_s",
        .match = 0xe0001053,
        .mask = 0xfff0707f,
        .operands = &.{ .rd, .rs1 },
        .variable_fields = &.{ .rd, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fcvt_s_w",
        .match = 0xd0000053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fcvt_s_wu",
        .match = 0xd0100053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fmv_w_x",
        .match = 0xf0000053,
        .mask = 0xfff0707f,
        .operands = &.{ .rd, .rs1 },
        .variable_fields = &.{ .rd, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fld",
        .match = 0x3007,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fsd",
        .match = 0x3027,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm12 },
        .variable_fields = &.{ .imm12hi, .rs1, .rs2, .imm12lo },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fmadd_d",
        .match = 0x2000043,
        .mask = 0x600007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fmsub_d",
        .match = 0x2000047,
        .mask = 0x600007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fnmsub_d",
        .match = 0x200004b,
        .mask = 0x600007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fnmadd_d",
        .match = 0x200004f,
        .mask = 0x600007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2, .rs3 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fadd_d",
        .match = 0x2000053,
        .mask = 0xfe00007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fsub_d",
        .match = 0xa000053,
        .mask = 0xfe00007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fmul_d",
        .match = 0x12000053,
        .mask = 0xfe00007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fdiv_d",
        .match = 0x1a000053,
        .mask = 0xfe00007f,
        .operands = &.{ .rd, .rm, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rm, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fsqrt_d",
        .match = 0x5a000053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fsgnj_d",
        .match = 0x22000053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fsgnjn_d",
        .match = 0x22001053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fsgnjx_d",
        .match = 0x22002053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fmin_d",
        .match = 0x2a000053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fmax_d",
        .match = 0x2a001053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fcvt_s_d",
        .match = 0x40100053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fcvt_d_s",
        .match = 0x42000053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "feq_d",
        .match = 0xa2002053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "flt_d",
        .match = 0xa2001053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fle_d",
        .match = 0xa2000053,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fclass_d",
        .match = 0xe2001053,
        .mask = 0xfff0707f,
        .operands = &.{ .rd, .rs1 },
        .variable_fields = &.{ .rd, .rs1 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fcvt_w_d",
        .match = 0xc2000053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fcvt_wu_d",
        .match = 0xc2100053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fcvt_d_w",
        .match = 0xd2000053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "fcvt_d_wu",
        .match = 0xd2100053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv_d},
    },
    .{
        .name = "lr_w",
        .match = 0x1000202f,
        .mask = 0xf9f0707f,
        .operands = &.{ .rd, .rs1, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "sc_w",
        .match = 0x1800202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amoswap_w",
        .match = 0x800202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amoadd_w",
        .match = 0x202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amoxor_w",
        .match = 0x2000202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amoand_w",
        .match = 0x6000202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amoor_w",
        .match = 0x4000202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amomin_w",
        .match = 0x8000202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amomax_w",
        .match = 0xa000202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amominu_w",
        .match = 0xc000202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "amomaxu_w",
        .match = 0xe000202f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv_a},
    },
    .{
        .name = "mulw",
        .match = 0x200003b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_m},
    },
    .{
        .name = "divw",
        .match = 0x200403b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_m},
    },
    .{
        .name = "divuw",
        .match = 0x200503b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_m},
    },
    .{
        .name = "remw",
        .match = 0x200603b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_m},
    },
    .{
        .name = "remuw",
        .match = 0x200703b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_m},
    },
    .{
        .name = "lwu",
        .match = 0x6003,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "ld",
        .match = 0x3003,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "sd",
        .match = 0x3023,
        .mask = 0x707f,
        .operands = &.{ .rs1, .rs2, .imm12 },
        .variable_fields = &.{ .imm12hi, .rs1, .rs2, .imm12lo },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "slli",
        .match = 0x1013,
        .mask = 0xfc00707f,
        .operands = &.{ .rd, .rs1, .shamtd },
        .variable_fields = &.{ .rd, .rs1, .shamtd },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "srli",
        .match = 0x5013,
        .mask = 0xfc00707f,
        .operands = &.{ .rd, .rs1, .shamtd },
        .variable_fields = &.{ .rd, .rs1, .shamtd },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "srai",
        .match = 0x40005013,
        .mask = 0xfc00707f,
        .operands = &.{ .rd, .rs1, .shamtd },
        .variable_fields = &.{ .rd, .rs1, .shamtd },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "addiw",
        .match = 0x1b,
        .mask = 0x707f,
        .operands = &.{ .rd, .rs1, .imm12 },
        .variable_fields = &.{ .rd, .rs1, .imm12 },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "slliw",
        .match = 0x101b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .shamtw },
        .variable_fields = &.{ .rd, .rs1, .shamtw },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "srliw",
        .match = 0x501b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .shamtw },
        .variable_fields = &.{ .rd, .rs1, .shamtw },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "sraiw",
        .match = 0x4000501b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .shamtw },
        .variable_fields = &.{ .rd, .rs1, .shamtw },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "addw",
        .match = 0x3b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "subw",
        .match = 0x4000003b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "sllw",
        .match = 0x103b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "srlw",
        .match = 0x503b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "sraw",
        .match = 0x4000503b,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .rs2 },
        .variable_fields = &.{ .rd, .rs1, .rs2 },
        .extensions = &.{.rv64_i},
    },
    .{
        .name = "fcvt_l_s",
        .match = 0xc0200053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv64_f},
    },
    .{
        .name = "fcvt_lu_s",
        .match = 0xc0300053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv64_f},
    },
    .{
        .name = "fcvt_s_l",
        .match = 0xd0200053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv64_f},
    },
    .{
        .name = "fcvt_s_lu",
        .match = 0xd0300053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv64_f},
    },
    .{
        .name = "fcvt_l_d",
        .match = 0xc2200053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv64_d},
    },
    .{
        .name = "fcvt_lu_d",
        .match = 0xc2300053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv64_d},
    },
    .{
        .name = "fmv_x_d",
        .match = 0xe2000053,
        .mask = 0xfff0707f,
        .operands = &.{ .rd, .rs1 },
        .variable_fields = &.{ .rd, .rs1 },
        .extensions = &.{.rv64_d},
    },
    .{
        .name = "fcvt_d_l",
        .match = 0xd2200053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv64_d},
    },
    .{
        .name = "fcvt_d_lu",
        .match = 0xd2300053,
        .mask = 0xfff0007f,
        .operands = &.{ .rd, .rm, .rs1 },
        .variable_fields = &.{ .rd, .rm, .rs1 },
        .extensions = &.{.rv64_d},
    },
    .{
        .name = "fmv_d_x",
        .match = 0xf2000053,
        .mask = 0xfff0707f,
        .operands = &.{ .rd, .rs1 },
        .variable_fields = &.{ .rd, .rs1 },
        .extensions = &.{.rv64_d},
    },
    .{
        .name = "lr_d",
        .match = 0x1000302f,
        .mask = 0xf9f0707f,
        .operands = &.{ .rd, .rs1, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "sc_d",
        .match = 0x1800302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amoswap_d",
        .match = 0x800302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amoadd_d",
        .match = 0x302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amoxor_d",
        .match = 0x2000302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amoand_d",
        .match = 0x6000302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amoor_d",
        .match = 0x4000302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amomin_d",
        .match = 0x8000302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amomax_d",
        .match = 0xa000302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amominu_d",
        .match = 0xc000302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "amomaxu_d",
        .match = 0xe000302f,
        .mask = 0xf800707f,
        .operands = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .variable_fields = &.{ .rd, .rs1, .rs2, .aq, .rl },
        .extensions = &.{.rv64_a},
    },
    .{
        .name = "fence_tso",
        .match = 0x8330000f,
        .mask = 0xfff0707f,
        .operands = &.{ .rs1, .rd },
        .variable_fields = &.{ .rs1, .rd },
        .extensions = &.{.rv_i},
    },
    .{
        .name = "pause",
        .match = 0x100000f,
        .mask = 0xffffffff,
        .operands = &.{},
        .variable_fields = &.{},
        .extensions = &.{.rv_i},
    },
    .{
        .name = "scall",
        .match = 0x73,
        .mask = 0xffffffff,
        .operands = &.{},
        .variable_fields = &.{},
        .extensions = &.{.rv_i},
    },
    .{
        .name = "sbreak",
        .match = 0x100073,
        .mask = 0xffffffff,
        .operands = &.{},
        .variable_fields = &.{},
        .extensions = &.{.rv_i},
    },
    .{
        .name = "fmv_x_s",
        .match = 0xe0000053,
        .mask = 0xfff0707f,
        .operands = &.{ .rd, .rs1 },
        .variable_fields = &.{ .rd, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "fmv_s_x",
        .match = 0xf0000053,
        .mask = 0xfff0707f,
        .operands = &.{ .rd, .rs1 },
        .variable_fields = &.{ .rd, .rs1 },
        .extensions = &.{.rv_f},
    },
    .{
        .name = "slli_rv32",
        .match = 0x1013,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .shamtw },
        .variable_fields = &.{ .rd, .rs1, .shamtw },
        .extensions = &.{.rv32_i},
    },
    .{
        .name = "srli_rv32",
        .match = 0x5013,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .shamtw },
        .variable_fields = &.{ .rd, .rs1, .shamtw },
        .extensions = &.{.rv32_i},
    },
    .{
        .name = "srai_rv32",
        .match = 0x40005013,
        .mask = 0xfe00707f,
        .operands = &.{ .rd, .rs1, .shamtw },
        .variable_fields = &.{ .rd, .rs1, .shamtw },
        .extensions = &.{.rv32_i},
    },
};

pub const Operand = enum {
    aq,
    fm,
    imm12,
    imm13,
    imm21,
    imm32,
    pred,
    rd,
    rl,
    rm,
    rs1,
    rs2,
    rs3,
    shamtd,
    shamtw,
    succ,
};

pub const Field = enum {
    aq,
    bimm12hi,
    bimm12lo,
    fm,
    imm12,
    imm12hi,
    imm12lo,
    imm20,
    jimm20,
    pred,
    rd,
    rl,
    rm,
    rs1,
    rs2,
    rs3,
    shamtd,
    shamtw,
    succ,
};

pub const Extension = enum {
    rv32_i,
    rv64_a,
    rv64_d,
    rv64_f,
    rv64_i,
    rv64_m,
    rv_a,
    rv_d,
    rv_f,
    rv_i,
    rv_m,
};
